name: "Version Builder"
description: "Generates/modifies version number based on version, branch and settings."
author: "Stephen Lautier"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "heart"
  color: "red"

# Define your inputs here.
inputs:
  version:
    required: false
    description: "Version to be used, if not specified will read from `package.json`."
    # default: "default value if applicable"
  force-preid:
    required: false
    description: "Forces preid versioning even if branch not satisfied."
    default: "false"
  force-stable:
    required: false
    description: "Forces non-preid versioning even if branch not satisfied."
    default: "false"
  preid-branches:
    required: false
    description:
      "Branches to be used for preid, as comma delimited to use for versioning
      e.g. 'master,develop'."
    default: "main,master,develop"
  preid:
    required: false
    description:
      "Version preid to append e.g. 'dev', if not specified will read from
      `package.json` or generated via branch name."
    # default: "default value if applicable"
  preid-num-delimiter:
    required: false
    description:
      "Delimiter for build number to use when using preid e.g. preid 'dev' with
      `.` delimiter be '1.0.0-dev.123' ('dev.123')."
    default: "."

# Define your outputs here.
outputs:
  version:
    description: "Build version generated e.g. '1.5.6-dev.123'."
  nonSemverVersion:
    description: "Omits the preid and returns just number e.g. '1.5.6'"
  majorVersion:
    description: "Returns the major version e.g. '1'"
  minorVersion:
    description: "Returns the minor version e.g. '5'"
  patchVersion:
    description: "Returns the patch version e.g. '6'"
  isPrerelease:
    description:
      "Returns whether the version is a prerelease version e.g. 'true' or
      'false'."

runs:
  using: "node20"
  main: "dist/index.js"
