name: "Version Builder"
description: "Generates/modifies version number based on version, branch and settings."
author: "Stephen Lautier"
inputs:
  version:
    required: false
    description: "Version to be used, if not specified will read from `package.json`."
    # default: "default value if applicable"
  preid-branches:
    required: false
    description: "Branches to be used for preid, as comma delimited to use for versioning e.g. 'master,develop'."
    default: "main,master,develop"
  preid:
    required: false
    description: "Version preid to append e.g. 'dev', if not specified will read from `package.json` or generated via branch name."
    # default: "default value if applicable"
  preid-num-delimiter:
    required: false
    description: "Delimiter for build number to use when using preid e.g. preid 'dev' with `.` delimiter be '1.0.0-dev.123' ('dev.123')."
    default: "."
runs:
  using: "node16"
  main: "dist/index.js"
