import { defineConfig } from "oxlint";

export default defineConfig({
	plugins: ["typescript", "import"],
	env: {
		node: true,
	},
	categories: {
		correctness: "error",
		restriction: "error",
		perf: "error",
		suspicious: "warn",
		style: "warn",
		pedantic: "off",
	},
	rules: {
		// https://oxc.rs/docs/guide/usage/linter/rules.html
		curly: ["error", "all", "consistent"],
		"prefer-const": "error",
		"prefer-template": "error",
		"sort-keys": "off",
		"func-style": ["error", "declaration", { allowArrowFunctions: true }],
		eqeqeq: "error",
		"no-var": "error",
		"no-console": "off",
		"no-process-exit": "off",
		"no-unused-vars": "off",
		"no-ternary": "off",
		"no-nested-ternary": "off",
		"no-continue": "off",
		"no-plusplus": "off",
		"no-magic-numbers": "off",
		"no-use-before-define": "off",
		"no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
		"init-declarations": "off",
		"max-statements": ["warn", { max: 40 }],
		"id-length": "off",
		"capitalized-comments": "off",
		"sort-imports": [
			"warn",
			{
				ignoreCase: true,
				ignoreDeclarationSort: true,
				ignoreMemberSort: true,
				memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
			},
		],
		"import/no-default-export": "off",
		"import/no-relative-parent-imports": "off",
		"import/exports-last": "off",
		"import/no-nodejs-modules": "off",
		"import/extensions": [
			"error",
			{
				ts: "never",
				tsx: "never",
				js: "never",
				jsx: "never",
			},
		],
		"import/no-namespace": ["error", { ignore: ["valibot"] }],
		"import/group-exports": "off",
		"import/no-named-export": "off",
		// "import/prefer-default-export": "off",
		"typescript/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
		"typescript/consistent-type-imports": ["error", { prefer: "type-imports" }],
		"typescript/no-explicit-any": "warn",
		"typescript/explicit-function-return-type": [
			"warn",
			{
				allowExpressions: true,
			},
		],
	},
});
